### ISSUE TITLE
logbook very slow

### ISSUE THREAD

**Issue by KaiDol** [inofix/flussbad-modules#301]
error loading .js file seems to prevent logbook from quick loading.

**Comment by chrberndt** [comment]
We can reproduce the issue but we don't think the js is the cause. We see Exceptions in the log when the logbook is requested, which we will have to investigate.

**Comment by chrberndt** [comment]
There is an issue with the project- / logbook article template which causes these exceptions. This will be fixed soon.

**Comment by chrberndt** [comment]
We have removed and re-created the logbook layout anew. Assetpublisher and categories-navigation have been redeployed. No more exceptions in catalina.out. Uncached logbook requests are now served well below 2 seconds which is fine for dynamically created pages.
